### ISSUE TITLE
Release file availability.

### ISSUE THREAD

**Issue by renard** [roikku/swift-explorer#56]
I would like to add swift-explorer into the Homebrew Cask project (https://github.com/caskroom/homebrew-cask).

My cask file is almost done, except for the download URL. Since the DMG file is hosted on google drive it is difficult to download it using a CLI tool.

Is it possible for you to distribute your binary files through bintray.com or something similar?

Thanks a lot.

**Comment by roikku** [comment]
https://bintray.com/roikku/generic/SwiftExplorer/

**Comment by renard** [comment]
Works GREAT.
Thanks for your reactivity.

FYI: https://github.com/caskroom/homebrew-cask/pull/15488

**Comment by vitorgalvao** [comment]
@roikku Homebrew-cask maintainer, here. We strive to make our casks always use official download links, as they are presented on the project’s homepage. Since you are now hosting this on bintray as well, would you consider making that the official download URL on the homepage, or is there some reason you’d rather keep using the google drive link?

**Comment by roikku** [comment]
Thanks for the suggestion. I have updated the project's homepage accordingly.

**Comment by vitorgalvao** [comment]
Thank you @roikku. Guess this issue can be closed, now.
